from pagelib import *
o = orig(4)
B = lambda k: o[k]["bbox"]

items = [
    text("p0004-b000", B("p0004-b000"), X(
         r"""refer to this difference as distribution shift. In this paper, we assume that for a predefined distribution on initial states $\statee_0 \sim \mathcal{W}$, the real-world trajectories $\trajreal_{\statee_0}$ are sampled from $\trajreal_{\statee_0} \sim \dist$, whereas the simulated trajectories $\trajsim_{\statee_0}$ are sampled from $\trajsim_{\statee_0} \sim \distzero$."""),
         join_previous="space"),
    heading("p0004-b001", B("p0004-b001"), "### 2.2 Surrogate Model: Reachability & Error Analysis"),
    text("p0004-b002", B("p0004-b002"), X(
         r"""A surrogate model $\overallf: \init \times \Theta \to \states^\horizon$, with trainable parameters $\theta \in \Theta$, can be trained by sampling $\horizon$-step trajectories $\trajsim_{\statee_0} \sim \distzero$ from the simulator to predict the trajectory $\trajsim_{\statee_{0}} \in \states^\horizon$ given its initial state $\statee_0 \in \init$. We call this dataset $\traindataset$, and we denote the predicted trajectory by,""")),
    text("p0004-b003", [88.0, 215.0, 529.0, 252.0], X(
         r"""$$\bar{\traj}_{\statee_{0}} = \overallf(\statee_{0}\ ; \theta),\ \text{where},\ \ \overallf(\statee_{0}\ ; \theta) = \left[\mathsf{F}^1(\statee_0), \ldots, \mathsf{F}^n(\statee_0), \ldots, \mathsf{F}^{(\horizon-1)n+1}(\statee_0), \ldots, \mathsf{F}^{n\horizon}(\statee_0)\right]^\top \tag{1}$$""")),
    text("p0004-b004", [89.0, 256.0, 523.0, 295.0], X(
         r"""where, $\mathsf{F}^{(\timeid-1)n+\ell}(\statee_0)$ is the $\ell^{th}$ state component at the $\timeid^{th}$ time-step in the trajectory $^{3}$. Let $e_\ell\in\reals^n$ denote the $\ell$-th basis vector of $\reals^n$. For a trajectory $\statee_1, \ldots \statee_\horizon$, and $\statee_0 \sim \mathcal{W}$, for $j =(\timeid-1)n+\ell$, we define the prediction errors as,""")),
    text("p0004-b005", B("p0004-b005"), X(
         r"""$$R^j = e_{\ell}^\top \statee_\timeid - \mathsf{F}^j(\statee_0), \quad \timeid \in[\horizon], \ell\in[n]. \tag{2}$$""")),
    text("p0004-b011", B("p0004-b011"),
         "Footnote 3: Here, the dimension and time steps are stacked into a single vector."),
    text("p0004-b006", B("p0004-b006"), X(
         r"""In this paper, we introduce the residual $\rho:\mathbb{R}^{n\horizon} \to \mathbb{R}_{\ge 0}$ as a function of the prediction errors $R^j$, where $j \in [n\horizon]$. In this section, we present a previously proposed example of such a function and later introduce an adjustment to reduce the conservatism in probabilistic reachability.""")),
    text("p0004-b007", B("p0004-b007"), X(
         r"""**Definition 1 (Simulation & Real Residual Distribution).** If the residual is generated by $\trajsim_{\statee_0}\sim \distzero$, we denote the residual distribution as $\ressim \sim \distzeroR$ where $\distzeroR$ is the simulation residual distribution. Conversely, if the residual is generated by $\trajreal_{\statee_0}\sim \dist$, we denote it as $\resreal \sim \distR$ where $\distR$ is the real residual distribution.""")),
    text("p0004-b008", B("p0004-b008"), X(
         r"""We also utilize total variation, Takezawa (2005) as a metric to quantify their distribution shift, $\tau\geq 0$. In other word, $\tau = \tv(\distzeroR, \distR)$, where $\tv$ refers to the total variation.""")),
    text("p0004-b009", B("p0004-b009"), X(
         r"""**Surrogate Flowpipe and Star-Set**. The surrogate flowpipe $\bar{X}\subset \reals^{n\horizon}$ is defined as a superset of the image of $\overallf(\init\ ;\theta)$. Formally, for all $\statee_0\in \init$, we need that $\overallf(\statee_0\ ;\theta) \in \bar{X}$. Due to the recent achievements in verifying neural networks with ReLU activations, we limit ourselves to the choice of ReLU neural networks as our surrogate models, and we rely on the NNV toolbox from Tran et al. (2020) to compute the surrogate flowpipe. Although other activation functions can be used, we anticipate more conservative results if non-ReLU activation functions are utilized. We choose to use NNV in our analysis here, because it can yield accurate reachability results in settings where neural networks with ReLU activation function are used. The approach in Tran et al. (2020) employs star-sets (an extension of zonotopes) to represent the reachable set and utilizes two main methods: (1) the exact-star method, which performs precise but slow computations, and (2) the approx-star method, which is faster but it is more conservative.""")),
    text("p0004-b010", B("p0004-b010"), X(
         r"""**Definition 2 (Star set Bak and Duggirala (2017)).** A star set $Y\subset \mathbb{R}^d$ is a tuple $\langle c, V, P \rangle$ where $c \in \mathbb{R}^d$ is the center, $V = \{v_1, v_2, \ldots, v_m \}$ is a set of $m$ vectors in $\mathbb{R}^d$ called basis""")),
    omit("p0004-b012", B("p0004-b012"), "4",
         "Printed page number 4 centred at the foot of the page; page furniture, checked on the 170 dpi render."),
]

save(4, items, r"""
Compared with the 170 dpi render, three 260 dpi crops (top third with (1) and (2); Definition 1 and the total-variation sentence;
Definition 2 and the footnote) and the TeX source (sections/prelim.tex). First item continues the paragraph from page 3 (join_previous
'space'). All inline and display mathematics taken from the TeX source with the authors' macros expanded (\trajsim ->
\sigma^{\mathsf{sim}}, \trajreal -> \sigma^{\mathsf{real}}, \distzero / \dist -> \mathcal{D}_{S,\mathrm{K}}^{\mathsf{sim}} /
^{\mathsf{real}}, \distzeroR / \distR -> \mathcal{J}_{S,\mathrm{K}}^{\mathsf{sim}} / ^{\mathsf{real}}, \overallf -> \mathcal{F},
\traindataset -> \mathcal{T}^{\mathsf{trn}}, \tv -> \mathsf{TV}, \horizon -> \mathrm{K}, \timeid -> k, \ressim = \resreal -> \rho) and
checked on the crops; TeX and PDF agree. The extractor's two formula images were replaced by LaTeX displays with the printed tags (1)
and (2); its glyph-soup text ('<sup>' tags, superscripts run into the prose) was replaced. In (1) the sans-serif component functions
$\mathsf{F}^1,\ldots,\mathsf{F}^{n\mathrm{K}}$ and the transpose are as printed; in (2) $R^j = e_\ell^\top s_k - \mathsf{F}^j(s_0)$ with
$k\in[\mathrm{K}],\ell\in[n]$. Heading '2.2 Surrogate Model: Reachability & Error Analysis' as ###. Theorem-like blocks: 'Definition 1
(Simulation & Real Residual Distribution).' and 'Definition 2 (Star set Bak and Duggirala (2017)).' are printed with a bold 'Definition
n', an upright parenthetical and a bold full stop; the whole label is written in bold. Their bodies are italic in the print and are
written upright here; Definition 1 ends at '... is the real residual distribution.' (end of the TeX environment). Definition 2 is cut by
the page break after 'called basis'; it continues on page 5 (join_previous 'space') and ends with display (3). Note: the same symbol
$\rho$ is used for the simulation residual and the real residual (the authors' macros \ressim and \resreal both print \rho); they are
told apart only by the distribution, $\rho\sim\mathcal{J}^{\mathsf{sim}}_{S,\mathrm{K}}$ or
$\rho\sim\mathcal{J}^{\mathsf{real}}_{S,\mathrm{K}}$. Printed wording kept: 'In other word', 'For a trajectory $s_1,\ldots s_\mathrm{K}$'
(no comma after the dots), '$\ell^{th}$', '$k^{th}$', 'function are used', 'Surrogate Flowpipe and Star-Set' as bold run-in title.
Footnote 3 (mark after 'trajectory', printed at the foot of the page) is placed after display (2), the end of the paragraph that
carries its mark; the mark is written ' $^{3}$'. Omitted: page number 4.
""")
