from pagelib import *
o = orig(8)
B = lambda k: o[k]["bbox"]

items = [
    figure("p0008-b000", [203.0, 88.0, 406.0, 196.2], "Figure 2", "figure-2"),
    caption("p0008-b001", [88.0, 196.6, 524.0, 303.0], X(
         r"""Figure 2: The figure shows the projection of prediction errors for two-dimensional states over a horizon of $\horizon = 2$. The left figure illustrates the projection on the $(R^1, R^2)$ axes (e.g., $k=1$), and the right figure displays the projection on the $(R^3, R^4)$ axes (e.g., $k=2$). This figure provides a comparison between the inflating hypercubes for a confidence level $\delta \in (0,1)$, generated by the PCA approach (red hypercubes) and the method proposed in Hashemi et al. (2024b) (green hypercubes). It clearly demonstrates the superior accuracy of the PCA technique compared to the other method. The principal axes for $k=1,2$ are $(r^1, r^2)$ and $(r^3, r^4)$, respectively.""")),
    text("p0008-b002", B("p0008-b002"), X(
         r"""The authors in Hashemi et al. (2024b) use the function in (5) to define the residual $\rho$ and compute the corresponding inflating hypercube $\delta X$. However, their technique imposes two conservative constraints. First, the center of the hypercube is always located at the origin. Second, the edges of the hypercube are restricted to be aligned with the direction of the trajectory state components.""")),
    text("p0008-b003", B("p0008-b003"), X(
         r"""To address these limitations, we propose an adjustment on the definition of the residual $\rho$ in equation (5), that enables us to overcome these issues. We integrate the concepts of Conformal Inference (CI) and Principal Component Analysis (PCA) in our new definition for the residual. This approach provides the principal axes as the orientation of inflating hypercube and noticeably reduces its size. In other words, our approach enhances the accuracy of conformal inference by manipulating the coordinate system, inspired by PCA. However, in the context of CI, altering the coordinate system has also been addressed in other works, such as Tumu et al. (2024); Sharma et al. (2024).""")),
    text("p0008-b004", B("p0008-b004"), X(
         r"""To obtain the principal axes, given the simulated trajectories from the training dataset $\trajsim_{\statee_{0,i}} \in \traindataset, i\in [|\traindataset|]$, for each segment $q\in[N]$, we use the trajectory segment $\trajsimseg{q}_{\statee_{0,i}}$ and its corresponding surrogate model $\overallf_q(\statee_{0,i}; \theta_q)$ to compute the corresponding set of prediction errors. Specifically, for each segment $q\in [N]$ and data index $i\in[|\traindataset|]$, we collect:""")),
    text("p0008-b005", B("p0008-b005"), X(
         r"""$$\PEsimseg{q}_i = \left[ \errsim{t_q n+1}_i, \errsim{t_q n+2}_i, \ldots, \errsim{(t_q+T_q)n}_i \right] \tag{9}$$""")),
    text("p0008-b006", B("p0008-b006"),
         "and approximate the average and covariance as follows:"),
    text("p0008-b007", B("p0008-b007"), X(
         r"""$$\overline{\PE}^{q} = \frac{\sum_{i=1}^{|\traindataset|} \PEsimseg{q}_i}{|\traindataset|} , \ \Sigma^q = \frac{\sum_{i=1}^{|\traindataset|} \left(\PEsimseg{q}_i - \overline{\PE}^{q}\right)^\top \left(\PEsimseg{q} - \overline{\PE}^{q}\right)}{|\traindataset|}. \tag{10}$$""")),
    text("p0008-b008", B("p0008-b008"), X(
         r"""We then apply spectral decomposition on the covariance matrix $\Sigma^q$ to obtain the array of eigenvectors $\eigvecseg{q} \in \mathbb{R}^{T_q n \times T_q n}$. Here, the principal axes for the trajectory segment $q \in [N]$ are centered on $\overline{\PE}^{q}$, and are aligned with the eigenvectors $\eigvecseg{q}_\ell, \ell \in [T_q n]$, which are the $\ell$-th columns of the matrix $\eigvecseg{q}$.""")),
    omit("p0008-b009", B("p0008-b009"), "8",
         "Printed page number 8 centred at the foot of the page; page furniture, checked on the 170 dpi render."),
]

save(8, items, r"""
Compared with the 170 dpi render, a 300 dpi crop of Figure 2 with margins, a 260 dpi crop of the lower third (paragraph 'To obtain the
principal axes ...' to the end of the page) and the TeX source (sections/PCA.tex). Figure 2 is printed at the top of the page, between
two complete paragraphs, and is kept there with its caption. Its crop contains both panels with the axis labels $R^1$, $R^2$, $R^3$,
$R^4$, the principal-axis labels $r^1$, $r^2$, $r^3$, $r^4$, the green and red dashed boxes and the in-figure panel labels 'time step
k = 1' and 'time step k = 2' (the figure is a raster image; these labels are not in the text layer). The crop bottom (196.2 pt) lies between the
panel labels (ink ends at 194.8 pt) and the first caption line (ink starts at 197.7 pt), measured on the 170 dpi render. Caption verbatim with LaTeX math
($\mathrm{K}=2$, $(R^1,R^2)$, $(R^3,R^4)$, $\delta\in(0,1)$, $k=1,2$, $(r^1,r^2)$, $(r^3,r^4)$). The two extractor formula images
were replaced by LaTeX displays with the printed tags (9) and (10), taken from the TeX source with macros expanded (\PEsimseg{q} ->
\mathsf{PE}^{q}, \errsim{x} -> R^{x}, \eigvecseg{q} -> \mathsf{V}^{q}, \traindataset -> \mathcal{T}^{\mathsf{trn}}; manual \! spacing
dropped) and checked symbol by symbol on the crop. SOURCE TYPOS KEPT in (10): the second factor of the covariance is printed
$(\mathsf{PE}^{q}-\overline{\mathsf{PE}}^{q})$ without the sample index $i$ (the first factor has $\mathsf{PE}^{q}_i$), and the
transpose is on the first factor although $\mathsf{PE}^q_i$ is written as a row in (9); TeX and PDF agree on both. References
resolved to the printed numbers: 'the function in (5)', 'equation (5)'. Inline math in the last paragraph: $\mathsf{V}^{q}\in
\mathbb{R}^{T_q n\times T_q n}$, $\overline{\mathsf{PE}}^{q}$, $\mathsf{V}^{q}_\ell,\ \ell\in[T_q n]$. Citations compared with the
render. Omitted: page number 8.
""")
