from pagelib import *
o = orig(10)
B = lambda k: o[k]["bbox"]

items = [
    text("p0010-b000", B("p0010-b000"), X(
         r"""**Proof.** The proof follows as the residual $\rho$ is the maximum of the normalized version of parameters $r^j, j\in n\horizon$ so that""")),
    text("p0010-b001", B("p0010-b001"), X(
         r"""$$\rho= \max \left(\ \frac{|r^1|}{\omega_1} ,\ \frac{|r^2|}{\omega_2} ,\ \ldots \ , \ \frac{|r^{n\horizon}|}{\omega_{n\horizon}}\ \right) \iff \bigwedge_{j=1}^{n\horizon} \left[ |r^j| \leq \rho \omega_j \right]. \tag{16}$$""")),
    text("p0010-b002", B("p0010-b002"), X(
         r"""Now, since $\Pr[ \rho \leq \rho^{\ast}_{\delta,\tau} ] \geq \delta$ as well as $\rho<\rho^*_{\delta,\tau} \iff |r^j|< \rho^*_{\delta,\tau} \omega_j$ for all $j\in [n\horizon]$, we can claim that $\Pr[ \bigwedge_{j=1}^{n\horizon} [ |r^j| \leq \rho^*_{\delta,\tau} \omega_j ]] \geq \delta$. The guarantee proposed in (15) is the reformulation of this results in terms of the division setting, $T_q, q\in [N]$. $\square$""")),
    text("p0010-b003", B("p0010-b003"), X(
         r"""Referring to Def. 2, and using the predicates $P_q(r^{t_qn+1},\ldots,r^{(t_q+T_q)n}), q\in[N]$ from Proposition 5 we can introduce the inflating hypercubes, $\delta X_q , q\in [N]$ as star sets. In other words, from equation (11), for any $q\in[N]$ we can compute the prediction errors as,""")),
    text("p0010-b004", B("p0010-b004"), X(
         r"""$$\PE^q = \overline{\PE}^q + \eigvecseg{q}\left[ r^{t_q n+1},r^{t_q n+2}, \ldots, r^{(t_q+T_q)n} \right] \tag{17}$$""")),
    text("p0010-b005", B("p0010-b005"), X(
         r"""which implies $\delta X_q = \langle \overline{\PE}^q, \eigvecseg{q}, P_q(r^{t_qn+1},\ldots,r^{(t_q+T_q)n}) \rangle$, and thus the concatenation of the star sets $\delta X_q$, serves as an inflating hypercube for $\PE$. Therefore, we denote the inflating hypercube of the entire trajectory by $\delta X = \langle \overline{\PE}, V, P \rangle$ where $V = \mathbf{diag}\left(V^1, \ldots, V^N\right)$ and $P = \bigwedge_{q=1}^N P_q$.""")),
    text("p0010-b006", B("p0010-b006"), X(
         r"""Finally, based on Lemma 3, the $\delta$-confident flowpipe on the entire trajectory $X$ can be obtained through the inflation of surrogate flowpipe $\bar{X}$ with the inflating hypercube $\delta X$, i.e., $X = \bar{X}\oplus \delta X$.""")),
    text("p0010-b007", B("p0010-b007"), X(
         r"""**Remark 6.** Figure 2 shows the advantage of the PCA approach by illustrating prediction errors of a $2$-dimensional state over $2$ consecutive time steps $^{5}$. This figure also provides a schematic of the inflating hypercubes generated by our residual definition and those generated by the definition proposed in (5). The primary function of the vectors $\overline{\PE}^q, q\in[N]$ is to reposition the surrogate reachsets $\bar{X}_q$ to locations that require minimal inflation, and the main role of $\eigvecseg{q}$ is to further reduce the necessary level of inflation.""")),
    text("p0010-b010", B("p0010-b010"), X(
         r"""Footnote 5: Division setting: $\horizon =2,\ n=2,\ N=2$, and $T_1=T_2= 1$.""")),
    heading("p0010-b008", B("p0010-b008"), "## 4 Numerical Evaluation"),
    text("p0010-b009", B("p0010-b009"), X(
         r"""To simulate real-world systems capable of producing actual trajectory data, we employ stochastic difference equation-based models with additive Gaussian noise to account for uncertainties in observations, dynamics, and potential modeling errors. Our theoretical guarantees apply to any real-world distribution $\trajreal_{\statee_0} \in \dist$, provided that the residual distribution shift $\tv(\distzeroR, \distR)$ is below a given threshold $\tau$. Here we evaluate our results on three different case studies. The first two experiments involve a 12-D quadcopter with $\tau = 0$, while the final experiment focuses on a 27-D powertrain model where the distribution shift is upper-bounded at $\tau =$ 4%. In Experiment 1, we compare our approach with Hashemi et al. (2024b). However, since that methodology does not scale well for trajectories with large number of time-steps, $\horizon$, we address Experiments 2 and 3, only using the methodology proposed in this paper. The next two sections provide a general overview of the experiments, with detailed information deferred to the Appendix. Table 1 also presents the details of the numerical results.""")),
    omit("p0010-b011", B("p0010-b011"), "10",
         "Printed page number 10 centred at the foot of the page; page furniture, checked on the 170 dpi render."),
]

save(10, items, r"""
Compared with the 170 dpi render, three 240-280 dpi crops covering the whole text area (proof and (16), (17); the star-set paragraph,
'Finally ...' and Remark 6; Section 4 and the footnote) and the TeX source (sections/PCA.tex, sections/Experiments.tex). The two
extractor formula images were replaced by LaTeX displays with the printed tags (16), (17); the surrounding glyph soup (including a
stray Markdown strikethrough in '$\delta X_q = \langle\overline{\mathsf{PE}}^q,\ldots$') was replaced by LaTeX from the TeX source with
macros expanded and \! spacing dropped; all formulas checked on the crops, TeX and PDF agree. Proof of Proposition 5: the label is
printed in italics ('Proof.') and is written '**Proof.**'; the printed end-of-proof square is written $\square$. Printed as is and kept:
'$r^j, j\in n\mathrm{K}$' (no brackets); (16) uses $\iff$ between '$\rho=\max(\ldots)$' and the conjunction of '$|r^j|\le\rho\omega_j$';
the proof text states $\Pr[\rho\le\rho^{\ast}_{\delta,\tau}]\ge\delta$ (non-strict, whereas page 9 and Proposition 5 have strict
inequalities '$\Pr[\rho<\rho^{\ast}_{\delta,\tau}]>\delta$' and '$>\delta$'), '$\rho<\rho^{\ast}_{\delta,\tau}\iff|r^j|<
\rho^{\ast}_{\delta,\tau}\omega_j$ for all $j$', and concludes $\Pr[\bigwedge_{j=1}^{n\mathrm{K}}[|r^j|\le\rho^{\ast}_{\delta,\tau}
\omega_j]]\ge\delta$; 'this results'. (17): $\mathsf{PE}^q=\overline{\mathsf{PE}}^q+\mathsf{V}^q[r^{t_qn+1},\ldots,r^{(t_q+T_q)n}]$. In
the paragraph after (17) the global hypercube is printed $\delta X=\langle\overline{\mathsf{PE}},V,P\rangle$ with italic $V =
\mathbf{diag}(V^1,\ldots,V^N)$ (not the sans-serif $\mathsf{V}^q$ used for the segments) - kept as printed. 'Def. 2', 'Proposition 5',
'equation (11)', 'Lemma 3', '(15)', '(5)', 'Figure 2', 'Table 1' are the printed reference numbers. 'Remark 6.' is bold in the print;
its body is italic (written upright) and ends at '... necessary level of inflation.' (end of the TeX environment). Footnote 5 (mark
after 'time steps' in Remark 6, printed at the foot of the page) is placed directly after Remark 6; mark written ' $^{5}$'. Heading '4
Numerical Evaluation' as ##. '$\tau = 4\%$' is written '$\tau =$ 4%' and '12-D', '27-D' as plain text so the numbers stay searchable.
Note for readers: Section 4 writes '$\sigma^{\mathsf{real}}_{s_0}\in\mathcal{D}^{\mathsf{real}}_{S,\mathrm{K}}$' with $\in$ (elsewhere
$\sim$). Omitted: page number 10.
""")
