#!/usr/bin/env python3
"""Reviewed items for PDF pages 6-10 of dietrich2024nonconvex (run to rewrite those page files)."""
from pagelib import T, H, C, O, F, TB, write_pages, RUNHEAD, PAGENO

PAGES, NOTES = {}, {}

# ----------------------------------------------------------------------------- page 6
NOTES[6] = r"""
Compared with the 170 dpi render, a 200 dpi crop of Figure 1 with extra margin and a 300 dpi crop of the text
with display (12). Running header and page number 6 omitted. The extractor had split Figure 1 into two images;
they are merged into one figure item whose bbox covers both panels (3-D surface plot on the left, contour plot
with axis tick labels -8..8 on the right); all four edges were checked on the wider crop and the caption is
outside the crop. Caption transcribed verbatim (gamma in LaTeX); the panels carry no in-figure text other than
tick labels. The paragraph after the caption continues the sentence from page 5 ('If m is larger than |
needed, Algorithm 2 ...'), join_previous = space; in the reading order Figure 1 and its caption are placed
before that paragraph so that the sentence is not interrupted. The extractor formula image is replaced by a $$
block: (12) minimize over mu, sigma the sum of sigma_i^2 subject to sum_{i=1}^m exp(-(1/2)(delta^{(j)} -
mu_i)^2 / sigma_i^2) - gamma >= 0, j = 1, ..., N, (comma printed) and sigma in [0, infinity)^m; exponent and
subscripts read on the 300 dpi crop. The support-scenario paragraph is rewritten from the render (the extractor
had glued '.Due to the nonconvex nature' into a superscript run). Kept as printed: 'Equation (12)' here versus
'(2)' without the word 'Equation' two lines later; 'a Apple M2 Pro'. Section heading '4. Examples' set to
level 2. The last paragraph ends with 'using a' and continues on page 7 after the Algorithm 2 float.
"""
PAGES[6] = [
    O("p0006-b000", RUNHEAD),
    F("p0006-b001", "Figure 1", "figure-1", [85, 86, 528, 246]),
    C("p0006-b003",
      r"Figure 1: (Left) Radial basis function generated by a set of data with the plane defined by the threshold "
      r"value, $\gamma$, (Right) the contour line (black), created by the intersection of the threshold plane with "
      r"the RBF, and the set of data (dark blue)."),
    T("p0006-b004",
      "needed, Algorithm 2 will produce disconnected sets. However, the unnecessary RBFs will only contain their "
      "initial center. This approach further allows us to produce disconnected reachable sets for systems that "
      "exhibit these dynamics. We write this as a constrained optimization problem:", join_previous="space"),
    T("p0006-b005",
      "$$\n"
      r"\begin{aligned}" "\n"
      r"\underset{\mu, \sigma}{\text{minimize}} \quad & \sum_{i=1}^{m} \sigma_i^2 \\" "\n"
      r"\text{subject to} \quad & \sum_{i=1}^{m} e^{-\frac{1}{2} \frac{(\delta^{(j)} - \mu_i)^2}{\sigma_i^2}} - \gamma "
      r"\ge 0, \quad j = 1, \ldots, N, \\" "\n"
      r"& \sigma \in [0, \infty)^m" "\n"
      r"\end{aligned} \tag{12}" "\n"
      "$$"),
    T("p0006-b006",
      r"We define a support scenario as any scenario, $\delta^{(j)}$, that changes the solution to Equation (12) when "
      r"removed from the set of all scenarios, $\delta^{(1)}, \ldots, \delta^{(N)}$. In other words, the removal of "
      r"$\delta^{(j)}$ results in different optimal widths, $\sigma$, of the calculated RBFs. It is worth noting that "
      r"the process of finding these support scenarios can be parallelized. By definition, this satisfies the "
      r"conditions needed to obtain the number of support scenarios, $s_N^*$. Due to the nonconvex nature of this "
      r"problem, we calculate $\epsilon$ a-posteriori using (2) with $s_N^*$. If the obtained value of $\epsilon$ "
      r"does not satisfy the necessary bounds, we iteratively increase the number of samples, $N$, and repeat the "
      r"process. This description is summarized in Algorithm 2."),
    H("p0006-b007", "## 4. Examples"),
    T("p0006-b008",
      "This section demonstrates the ability of the presented data-driven approaches to accurately estimate the "
      "forward reachable sets of two numerical examples posed in (Devonport et al., 2021). We evaluate Algorithms 1 "
      "and 2, to expose extensions of scenario optimization, but we do not attempt to compare these methods. All "
      "computations were done on a Apple M2 Pro, 12-core CPU. One Python thread was run to compute all tiling "
      "problems, while ten Python threads were used in computing the radial basis functions."),
    T("p0006-b009",
      r"To verify that the computed reachable sets in the following examples satisfy the guarantee that they are "
      r"$\epsilon$-accurate, we compute an a-posteriori empirical estimate of the reachable set using a"),
    O("p0006-b010", PAGENO),
]

# ----------------------------------------------------------------------------- page 7
NOTES[7] = r"""
Compared with the 170 dpi render, 300 dpi crops of the two halves of the Algorithm 2 box, 450-500 dpi crops of
lines 2, 10-12 and 19-23, and a 280 dpi crop of the text below. Running header and page number 7 omitted. The
extractor had fragmented Algorithm 2 into eighteen list items with broken exponents; they are replaced by one
image crop (figure item, asset algorithm-2, both rules inside the crop) followed by a text transcription: bold
printed title line, one paragraph per printed line with the printed line numbers 1-23, nesting shown by
'&emsp;&emsp;' per level as read from the printed indentation (level 1: lines 5-7, 13-15, 22; level 2: lines
8-12, 16, 17, 20, 21; level 3: lines 18, 19). Kept as printed in the algorithm, read on the 450-500 dpi crops:
lower-case phi for the transition function (Algorithm 1 input has capital Phi); 'mu_i, ..., mu_m' with first
index i in lines 2 and 23; lines 8-12 are printed inside the for loop of line 7 (so k-means in line 10 is inside
the loop); line 11 has a single exponential with index i (no sum over the m RBFs as in (12)); line 12 'If c >=
0, then set sigma_i = 0. Else set sigma_i = infinity.'; line 18 uses mu_j and sigma_j with the sample index j;
line 21 'If Sigma_i = Sigma, then S = S + 1.' (printed with an equals sign, although the text on page 6 defines
a support scenario as one whose removal changes the solution); 'using Equation 2' without parentheses; no 'end'
lines. The paragraph below the box continues the sentence from page 6 ('using a | one-sided Chernoff bound'),
join_previous = space; in the reading order Algorithm 2 is placed at the end of Section 3.2 (after 'This
description is summarized in Algorithm 2.') so that the sentence is not interrupted. Inline mathematics
transcribed from the 280 dpi crop: '46, 052' is printed in math mode with a space after the comma and written
46,052; '.01' printed without leading zero; Duffing dynamics 'x-double-dot = -alpha y + x - x^3 + gamma
cos(omega t)' (a single second-order equation in x in which the state y appears, as printed), parameter values
and initial intervals. Heading '4.1. Duffing Oscillator' set to level 3; '4.1.1. TILING WITH BASIS FUNCTIONS'
(small capitals) written in title case at level 4. Kept as printed: upright 'A' and the letter 'x' as product
sign in 'A = [-5, 5] x [-5, 5]' and '20x20 grid'. The last paragraph ends with 'which took 1.70' and continues
on page 8 after the Figure 2 float.
"""
RBF_I = r"e^{-\frac{1}{2} \frac{(\delta^{(i)} - \mu_i)^2}{\sigma_i^2}}"
RBF_J = r"e^{-\frac{1}{2} \frac{(\delta^{(j)} - \mu_j)^2}{\sigma_j^2}}"
E1, E2, E3 = "&emsp;&emsp;", "&emsp;&emsp;" * 2, "&emsp;&emsp;" * 3
ALG2 = "\n\n".join([
    r"**Algorithm 2** : Scenario reachability with radial basis functions",
    r"1: **Input**: Black-box transition function model $\phi(t_1; t_0, x_0, d)$; Random variables $X_0$ and $D$; "
    r"Threshold $\Gamma$; Number of RBFs $m$; Batch size $B$; Confidence parameter $\beta \in (0, 1)$.",
    r"2: **Output**: $\Sigma = \{\sigma_1, ..., \sigma_m\}$ corresponding to optimal widths of RBFs; $\mu_i, \ldots, "
    r"\mu_m$ corresponding to centers of RBFs; Robustness against constraint violation $\epsilon$.",
    r"3: **Initialize** number of support scenarios, $S = 0$.",
    r"4: **while** $\epsilon$ is large **do**",
    "5: " + E1 + r"$N = (B \cdot \text{number of iterations})$",
    "6: " + E1 + r"**Step 1:**",
    "7: " + E1 + r"**for all** $i \in \{1, ..., N\}$ **do**",
    "8: " + E2 + r"Take samples $x_{0i} \sim X_0, d_i \sim D$",
    "9: " + E2 + r"Evaluate $\delta^{(i)} = \phi(t_1; t_0, x_{0i}, d_i)$",
    "10: " + E2 + r"Take $\gamma = \Gamma$; $\mu_1, \ldots, \mu_m =$ k-means($m$ clusters); and $\sigma_1, \ldots, "
    r"\sigma_m$ to be arbitrary",
    "11: " + E2 + r"Evaluate $c = " + RBF_I + r" - \gamma$",
    "12: " + E2 + r"If $c \ge 0$, then set $\sigma_i = 0$. Else set $\sigma_i = \infty$.",
    "13: " + E1 + r"Let $\Sigma = \{\sigma_1, \ldots, \sigma_m\}$ be the set of optimal widths of the calculated RBFs "
    r"from Step 1.",
    "14: " + E1 + r"**Step 2:**",
    "15: " + E1 + r"**for all** $i \in \{1, ..., N\}$ **do**",
    "16: " + E2 + r"Remove sample $\delta^{(i)}$ from $\delta^{(1)}, \ldots, \delta^{(N)}$ taken from Step 1",
    "17: " + E2 + r"**for all** $j \in \{1, ..., N\} \setminus i$ **do**",
    "18: " + E3 + r"Evaluate $c = " + RBF_J + r" - \gamma$",
    "19: " + E3 + r"If $c \ge 0$, then set $\sigma_j = 0$. Else set $\sigma_j = \infty$.",
    "20: " + E2 + r"Let $\Sigma_i = \{\sigma_1, \ldots, \sigma_m\}$ be the set of optimal widths of the RBFs without "
    r"scenario $\delta^{(i)}$.",
    "21: " + E2 + r"If $\Sigma_i = \Sigma$, then $S = S + 1$.",
    "22: " + E1 + r"**calculate** $\epsilon$ using Equation 2 where $s_N^* = S$.",
    r"23: **return** $\Sigma$; $\mu_i, \ldots, \mu_m$; $\epsilon$.",
])
ALG2_BOX = [86, 88, 526, 475]
PAGES[7] = [
    O("p0007-b000", RUNHEAD),
    F("p0007-alg2", "Algorithm 2", "algorithm-2", ALG2_BOX),
    T("p0007-alg2-text", ALG2, bbox=ALG2_BOX),
    T("p0007-b019",
      r"one-sided Chernoff bound (Tempo et al., 2012). This ensures that the a-posteriori estimate of the reachable "
      r"set given an additional $46,052$ samples exceeds the true measure by no more than $.01$ with confidence "
      r"$0.9999$. The results are shown in Tables 1 and 2 and validate that the reachable sets are indeed "
      r"$\epsilon$-accurate.", join_previous="space"),
    H("p0007-b020", "### 4.1. Duffing Oscillator"),
    T("p0007-b021",
      r"The first example is a reachable set estimation problem for the nonlinear, time-varying system with dynamics: "
      r"$\ddot{x} = -\alpha y + x - x^3 + \gamma \cos(\omega t)$, with states $x, y \in \mathbb{R}$ and parameters "
      r"$\alpha, \gamma, \omega \in \mathbb{R}$. This system is known as the Duffing oscillator, a nonlinear "
      r"oscillator which exhibits chaotic behavior for certain values of $\alpha, \gamma$ and $\omega$, for instance "
      r"$\alpha = 0.05, \gamma = 0.4, \omega = 1.3$. The set of initial states is the interval such that $x(0) \in "
      r"[0.95, 1.05]$, $y(0) \in [-0.05, 0.05]$, and we take $X_0$ to be the uniform random variable over this "
      r"interval. The time range is $[t_0, t_1] = [0, 100]$."),
    H("p0007-b022", "#### 4.1.1. Tiling with Basis Functions"),
    T("p0007-b023",
      r"We take A to be the hyperrectangle $A = [-5, 5]$ x $[-5, 5]$ and partition A into a 20x20 grid. We take $N = "
      r"1000$ samples and $\beta = 10^{-9}$. The output of Algorithm 1 for this problem, which took 1.70"),
    O("p0007-b024", PAGENO),
]

# ----------------------------------------------------------------------------- page 8
NOTES[8] = r"""
Compared with the 170 dpi render, a 220 dpi crop of Figure 2 with extra margin and a 260 dpi crop of the text.
Running header and page number 8 omitted. The extractor had split Figure 2 into two overlapping images; they are
merged into one figure item covering both panels with their axis tick labels and axis letters (left: tiling
plot, axes X and Y; right: RBF plot with orange crosses, axes x and y); edges checked on the wider crop, caption
outside. Caption verbatim ('N=1000' is printed in text type without spaces, R^2 in LaTeX). The paragraph after
the caption continues the sentence from page 7 ('which took 1.70 | seconds to compute'), join_previous = space;
in the reading order Figure 2 and its caption follow this paragraph. The extractor had pushed several runs of
both result paragraphs into <sup> tags and glued words; both are rewritten from the 260 dpi crop. Numbers
checked digit by digit: s_N^* = 67, epsilon = 0.2509, 74.91%, 100 trials, 63 and 72, 25.09%; m = 2, gamma =
0.25, N = 1000, beta = 10^{-9}, 7 minutes, s_N^* = 19, epsilon = 0.1182, 88.82%, 5 and 24, 10.34%. The
percentages 74.91% and 88.82% are printed in math type and written as plain text so that they stay searchable.
Kept as printed: the quotation marks of ”one in a billion” are two closing marks; 'convexity refined nonconvex
approach'. '4.1.2. RADIAL BASIS FUNCTIONS' (small capitals) written in title case at level 4; '4.2. Quadrotor
Model' at level 3. The extractor formula image is replaced by a $$ block for (13); 'sin' and 'cos' are printed
in math italic (not as operators) and are transcribed as plain letters to match. The last paragraph ends with
'the desired' and continues on page 9 after the Table 1 float.
"""
PAGES[8] = [
    O("p0008-b000", RUNHEAD),
    F("p0008-b001", "Figure 2", "figure-2", [85, 85, 528, 246]),
    C("p0008-b003",
      r"Figure 2: Duffing Oscillator problem in $\mathbb{R}^2$: (Left) Enlarged view of reachable set (light blue) "
      r"using a grid-based partition and N=1000 samples (dark blue). (Right) Reachable set (purple) and support "
      r"scenarios (orange) using two radial basis functions and N=1000 samples (dark blue)."),
    T("p0008-b004",
      r"seconds to compute, is shown on the left in Figure 2. We calculate the number of support scenarios, $s_N^* = "
      r"67$, and $\epsilon = 0.2509$ a-posteriori to get the probability that our tiling contains at least 74.91% of "
      r"the reachable set distribution, with a ”one in a billion” chance of failure. We performed 100 trials of the "
      r"same experiment and the number of support scenarios was always between 63 and 72. On average, the "
      r"probabilistic volume outside the reachable set did not exceed 25.09% under the convexity refined nonconvex "
      r"approach. Additionally, we utilize the wait-and-judge perspective to investigate the effect of a larger $N$ "
      r"on $\epsilon$. The results are shown in Table 1.", join_previous="space"),
    H("p0008-b005", "#### 4.1.2. Radial Basis Functions"),
    T("p0008-b006",
      r"We take $m = 2$, such that we will calculate two radial basis functions. We set the initial centers of the "
      r"RBFs to be close to optimal using a k-means clustering algorithm and allow the widths of our RBF to be chosen "
      r"arbitrarily. We take $\gamma = 0.25$ to be the threshold of our RBF, $N = 1000$ samples, and $\beta = "
      r"10^{-9}$. The output of Algorithm 2 for this problem, which took approximately 7 minutes to compute, is shown "
      r"on the right in Figure 2. We calculate the number of support scenarios, $s_N^* = 19$, and $\epsilon = 0.1182$ "
      r"a-posteriori to get the probability that our radial basis functions contain at least 88.82% of the reachable "
      r"set distribution, with a ”one in a billion” chance of failure. We performed 100 trials of the same experiment "
      r"and the number of support scenarios was always between 5 and 24. On average, the probabilistic volume outside "
      r"the reachable set did not exceed 10.34% under the nonconvex approach. Additionally, we utilize the "
      r"wait-and-judge perspective to investigate the effect of a larger $N$ on $\epsilon$. The results are shown in "
      r"Table 1."),
    H("p0008-b007", "### 4.2. Quadrotor Model"),
    T("p0008-b008",
      "The next example is a reachable set estimation problem for a nonlinear model of a quadrotor used as an example "
      "in (Mitchell et al., 2019) and (Bouffard, 2012). The dynamics for this system are"),
    T("p0008-b009",
      "$$\n"
      r"\ddot{x} = u_1 K sin(\theta), \quad \ddot{h} = -g + u_1 K cos(\theta), \quad \ddot{\theta} = -d_0 \theta - "
      r"d_1 \dot{\theta} + n_0 u_2 \tag{13}" "\n"
      "$$"),
    T("p0008-b010",
      r"where $x$ and $h$ denote the quadrotor’s horizontal position and altitude in meters, respectively, and "
      r"$\theta$ denotes its angular displacement. The system has 6 states, which we take to be $x, h, \theta$, and "
      r"their first derivatives. The two system inputs $u_1$ and $u_2$ represent the motor thrust and the desired"),
    O("p0008-b011", PAGENO),
]

# ----------------------------------------------------------------------------- page 9
NOTES[9] = r"""
Compared with the 170 dpi render and with 260-300 dpi crops of Table 1, of the text with display (14), of
Figure 3 (with extra margin) and of the 4.2.1 paragraph. Running header and page number 9 omitted. Table 1 is
captured as cells (7 rows x 5 columns incl. header), every cell compared with the 260 dpi crop: the first
header cell is empty in the print; the row-group label ('Duffing Oscillator: Tiling' / 'Duffing Oscillator:
RBF') and the value in the 'Estimate' column are printed once per group of three rows, on the first row, and
the other cells of those columns are left empty as printed; the header symbol is written as the character ϵ
(the builder doubles backslashes in table cells, so LaTeX is avoided there); '(1)/(2)' in the header 'Run Time
of (1)/(2)' are printed as hyperlinks (they refer to Algorithms 1 and 2); '.999966' and '.999971' printed
without leading zero; run times '1.70s' etc. printed without space. Caption verbatim ('a-posterior' as
printed). The paragraph after the caption continues the sentence from page 8 ('the desired | angle,
respectively'), join_previous = space; in the reading order Table 1 and its caption are placed at the end of
Section 4.1.2, where the table is cited. The extractor formula image is replaced by a $$ block for (14): two
rows of three interval memberships, each ending with a comma, the second row with dotted x, h, theta (dots read
on the 300 dpi crop). Inline mathematics from the crop: g = 9.81, K = 0.89/1.4, d_0 = 70, d_1 = 17, n_0 = 55;
u_1(t) = u_1, u_2(t) = u_2 for all t in [t_0, t_1]; u_1 in [-1.5 + g/K, 1.5 + g/K], u_2 in [-pi/4, pi/4];
[t_0, t_1] = [0, 5]. The two extractor images of Figure 3 are merged into one figure item covering both panels
with tick labels and axis letters; edges checked on the wider crop. The Figure 3 caption was an ordinary text
item in the extractor output and is now a caption item; 'positon' is a misprint of the paper and is kept.
'4.2.1. TILING WITH BASIS FUNCTIONS' written in title case at level 4. Numbers of the last paragraph checked:
[-100, 100]^6, 10 sides, N = 1000, beta = 10^{-9}, 6.28 seconds, s_N^* = 19, epsilon = 0.1125, 88.75% (printed
in math type, written as plain text). The paragraph ends with '”one in a billion” chance' and continues on page 10.
"""
PAGES[9] = [
    O("p0009-b000", RUNHEAD),
    TB("p0009-b001", "Table 1", "table-1", [
        ["", "Sample Size", "Run Time of (1)/(2)", "ϵ", "Estimate"],
        ["Duffing Oscillator: Tiling", "N = 1000", "1.70s", "0.251", ".999966"],
        ["", "N = 3000", "2.49s", "0.117", ""],
        ["", "N = 5000", "3.48s", "0.078", ""],
        ["Duffing Oscillator: RBF", "N = 1000", "7 min", "0.118", ".999971"],
        ["", "N = 2000", "11 min", "0.033", ""],
        ["", "N = 3000", "22 min", "0.035", ""],
    ]),
    C("p0009-b002",
      r"Table 1: Computation times and a-posterior calculation of $\epsilon$ for reachable sets of $N$ samples of "
      r"Duffing Oscillator, and empirical estimates of the reachable sets (in Figure 2) using a one-sided Chernoff "
      r"bound."),
    T("p0009-b003",
      r"angle, respectively. The parameter values used (following (Bouffard, 2012)) are $g = 9.81, K = 0.89/1.4, d_0 = "
      r"70, d_1 = 17, n_0 = 55$. The set of initial states is the interval such that", join_previous="space"),
    T("p0009-b004",
      "$$\n"
      r"\begin{aligned}" "\n"
      r"x(0) &\in [-1.7, 1.7], & h(0) &\in [0.3, 2.0], & \theta(0) &\in [-\pi/12, \pi/12], \\" "\n"
      r"\dot{x}(0) &\in [-0.8, 0.8], & \dot{h}(0) &\in [-1.0, 1.0], & \dot{\theta}(0) &\in [-\pi/2, \pi/2]," "\n"
      r"\end{aligned} \tag{14}" "\n"
      "$$"),
    T("p0009-b005",
      r"the set of inputs is the set of constant functions $u_1(t) = u_1$, $u_2(t) = u_2\ \forall t \in [t_0, t_1]$, "
      r"whose values lie in the interval $u_1 \in [-1.5 + g/K, 1.5 + g/K], u_2 \in [-\pi/4, \pi/4]$, and we take "
      r"$X_0$ and $D$ to be the uniform random variables defined over these intervals. The time range is $[t_0, t_1] "
      r"= [0, 5]$."),
    F("p0009-b006", "Figure 3", "figure-3", [85, 397, 528, 548]),
    C("p0009-b008",
      "Figure 3: Reachable set estimates for the horizontal positon and altitude of the planar quadrotor model: "
      "(Left) Enlarged view of reachable set (light blue) using a grid-based partition and N=1000 samples (dark "
      "blue). (Right) Reachable set (purple) and support scenarios (orange) using three radial basis functions and "
      "N=1000 samples (dark blue)."),
    H("p0009-b009", "#### 4.2.1. Tiling with Basis Functions"),
    T("p0009-b010",
      r"We take A to be the hyperrectangle $A = [-100, 100]^6$ and partition A to be the grid with 10 sides along "
      r"each dimension. We take $N = 1000$ samples and $\beta = 10^{-9}$. The output of Algorithm 1 for this problem, "
      r"which took 6.28 seconds to compute, is shown on the left in Figure 3. We calculate the number of support "
      r"scenarios, $s_N^* = 19$, and $\epsilon = 0.1125$ a-posteriori to get the probability that our tiling contains "
      r"at least 88.75% of the reachable set distribution, with a ”one in a billion” chance"),
    O("p0009-b011", PAGENO),
]

# ----------------------------------------------------------------------------- page 10
NOTES[10] = r"""
Compared with the 170 dpi render and 260 dpi crops of Table 2 and of the two text blocks. Running header and
page number 10 omitted. The first paragraph continues the sentence from page 9 ('chance | of failure'),
join_previous = space. Table 2 is captured as cells (7 rows x 5 columns incl. header), every cell compared with
the crop; as in Table 1 the first header cell is empty, the row-group label ('Quadrotor: Tiling' / 'Quadrotor:
RBF') and the 'Estimate' value are printed only on the first row of each group and the remaining cells of those
columns are empty as printed, and the header symbol is written as the character ϵ. Run times are printed with
a space here ('6.28 s', '3.3 hr'), unlike Table 1. The Table 2 caption was an ordinary text item in the
extractor output and is now a caption item ('a-posterior' as printed). '4.2.2. RADIAL BASIS FUNCTIONS' written
in title case at level 4 (extractor had level 2); '5. Conclusion' and 'Acknowledgments' set to level 2
(extractor had level 1). Numbers checked digit by digit: 100 trials, 18 and 22, 11.6%; m = 3, gamma = 0.25, N =
1000, beta = 10^{-9}, 30 minutes, s_N^* = 22, epsilon = 0.1253, 87.47% (printed in math type, written as plain
text), 14 and 31, 11.8%; grant numbers CNS-2111688, FA5590-21-1-0529, FA9550-21-1-0288. Kept as printed: closing
quotation marks on both sides of ”one in a billion”.
"""
PAGES[10] = [
    O("p0010-b000", RUNHEAD),
    T("p0010-b001",
      r"of failure. We performed 100 trials of the same experiment and the number of support scenarios remained "
      r"between 18 and 22. On average, the probabilistic volume outside the reachable set did not exceed 11.6% under "
      r"the convexity refined nonconvex approach. Additionally, we investigate the effect of a larger $N$ on "
      r"$\epsilon$. The results are shown in Table 2.", join_previous="space"),
    TB("p0010-b002", "Table 2", "table-2", [
        ["", "Sample Size", "Run Time of (1)/(2)", "ϵ", "Estimate"],
        ["Quadrotor: Tiling", "N = 1000", "6.28 s", "0.113", ".999997"],
        ["", "N = 3000", "8.07 s", "0.050", ""],
        ["", "N = 5000", "8.37 s", "0.032", ""],
        ["Quadrotor: RBF", "N = 1000", "30 min", "0.125", ".999923"],
        ["", "N = 2000", "3.3 hr", "0.065", ""],
        ["", "N = 3000", "5.5 hr", "0.051", ""],
    ]),
    C("p0010-b003",
      r"Table 2: Computation times and a-posterior calculation of $\epsilon$ for reachable sets of $N$ samples of "
      r"Quadrotor, and empirical estimates of the reachable sets (in Figure 3) using a one-sided Chernoff bound."),
    H("p0010-b004", "#### 4.2.2. Radial Basis Functions"),
    T("p0010-b005",
      r"We take $m = 3$, such that we will calculate three radial basis functions. We set the initial centers of the "
      r"RBFs to be close to optimal using a k-means clustering algorithm and allow the widths of our RBF to be chosen "
      r"arbitrarily. We take $\gamma = 0.25$ to be the threshold of our RBF, $N = 1000$ samples, and $\beta = "
      r"10^{-9}$. The output of Algorithm 2 for this problem, which took approximately 30 minutes to compute, is shown "
      r"on the right in Figure 3. We calculate the number of support scenarios, $s_N^* = 22$, and $\epsilon = 0.1253$ "
      r"a-posteriori to get the probability that our radial basis functions contain at least 87.47% of the reachable "
      r"set distribution, with a ”one in a billion” chance of failure. We performed 100 trials of the same experiment "
      r"and the number of support scenarios was always between 14 and 31. On average, the probabilistic volume outside "
      r"the reachable set did not exceed 11.8% under the nonconvex approach. Additionally, we utilize the "
      r"wait-and-judge perspective to investigate the effect of a larger $N$ on $\epsilon$. The results are shown in "
      r"Table 2."),
    H("p0010-b006", "## 5. Conclusion"),
    T("p0010-b007",
      "We presented a method of nonconvex scenario optimization for reachability analysis. This approach does not "
      "require a-priori sample complexity bounds and significantly decreases the computational cost in finding "
      "reachable sets. We first provided a partition-based instance of scenario reachability that is computationally "
      "efficient and scales well to higher state dimensions. We then provided an estimation of reachable sets using "
      "radial basis functions."),
    H("p0010-b008", "## Acknowledgments"),
    T("p0010-b009",
      "This work was supported in part by the National Science Foundation grant CNS-2111688, Air Force Office of "
      "Scientific Research grants FA5590-21-1-0529 and FA9550-21-1-0288, and by a National Science Foundation "
      "Graduate Research Fellowship."),
    O("p0010-b010", PAGENO),
]

if __name__ == "__main__":
    write_pages(PAGES, NOTES)
