from pagelib import *

AP = "AutoPassing (12 vers, 13 edges)"
MG = "Merge (7 vers, 7 edges)"
M3 = "Merge3 (6 vers, 5 edges)"
rows = [
    ["Model", "TH", "Initial set", "U", "Ref", "Safe", "Runtime"],
    ["Powertrn (5 vers, 6 edges)", "80", "λ ∈ [14.6, 14.8]", "U_p", "2", "✓", "217.4s"],
    [AP, "50", "sy_A ∈ [-1, 1] sy_B ∈ [14, 16]", "U_c", "4", "✓", "208.4s"],
    [AP, "50", "sy_A ∈ [-1, 1] sy_B ∈ [4, 6.5]", "U_c", "5", "✗", "152.5s"],
    [MG, "50", "sx_A ∈ [-5, 5] sy_B ∈ [-2, 2]", "U_c", "0", "✓", "55.0s"],
    [MG, "50", "sx_A ∈ [-5, 5] sy_B ∈ [2, 10]", "U_c", "-", "✗", "38.7s"],
    [M3, "50", "sy_A ∈ [-3, 3] sy_B ∈ [14, 23] sy_C ∈ [36, 45]", "U_c", "4", "✓", "197.6s"],
    [M3, "50", "sy_A ∈ [-3, 3] sy_B ∈ [14, 15] sy_C ∈ [16, 20]", "U_c", "-", "✗", "21.3s"],
    ["ATS (4 vers, 3 edges)", "50", "Erpm ∈ [900, 1000]", "U_t", "2", "✓", "109.2s"],
]

items = [
    text("p0014-b002", [133.0, 325.0, 478.0, 358.0],
         r"overtakes B (bottom plot). The unsafe set $(|sx_A-sx_B|<2 \ \&\ |sy_A-sy_B|<2)$ is proved to be disjoint from computed reachtube. With a different initial set, $sy_B \in [30, 40]$, DryVR finds counter-example (Figure 2b).",
         join_previous="space"),
    table("p0014-b000", [132.5, 124.5, 479.0, 282.5], "Table 1", "table-1", rows),
    caption("p0014-b001", [133.0, 288.0, 478.0, 319.0],
            r"Table 1: Safety verification results. Numbers below benchmark names: # vertices and edges of $G$, TH: duration of shortest path in $G$, Ref: # refinements performed; Runtime: overall running time."),
    text("p0014-tnote", [133.0, 284.0, 478.0, 287.5],
         r"*[Conversion note on Table 1: in the printed table the Model cell of AutoPassing, Merge and Merge3 spans two rows (benchmark name in the first, the vertex/edge counts in the second); in the CSV the full label, e.g. 'AutoPassing (12 vers, 13 edges)', is repeated in both rows. The column header 'U' is the calligraphic unsafe-set symbol $\mathcal{U}$, and 'U_p', 'U_c', 'U_t' are $\mathcal{U}_p$, $\mathcal{U}_c$, $\mathcal{U}_t$; 'sy_A' etc. are $sy_A$, $sx_A$, $sy_B$, $sy_C$; the minus signs of the intervals are written with the ASCII hyphen. In the Safe column the printed check mark is '✓' and the printed cross is '✗'; '-' in the Ref column is printed as a hyphen. Two intervals in one cell are printed side by side without a separator; the third interval of the Merge3 rows is printed on a second line of the cell.]*"),
    text("p0014-b003", [133.0, 359.0, 478.0, 459.0],
         r"Table 1 summarizes some of the verification results obtained using DryVR. $\mathsf{ATS}$ is an automatic transmission control system (see Appendix A.2 for more details). These experiments were performed on a laptop with Intel Core i7-6600U CPU and 16 GB RAM. The initial range of only the salient continuous variables are shown in the table. The unsafe sets are discussed with the model description. For example $\mathcal{U}_c$ means two vehicles are too close. For all the benchmarks, the algorithm terminated in a few minutes which includes the time to simulate, learn discrepancy, generate reachtubes, check the safety of the reachtube, over all refinements."),
    text("p0014-b004", [133.0, 460.0, 478.0, 538.0],
         r"For the results presented in Table 1, we used GED. The reachtube generated by PED for $\mathsf{Powertrn}$ is more precise, but for the rest, the reachtubes and the verification times using both GED and PED were comparable. In addition to the $\mathit{VerifySafety}$ algorithm, DryVR also looks for counter-examples by quickly generating random executions of the hybrid system. If any of these executions is found to be unsafe, DryVR will return “Unsafe” without starting the $\mathit{VerifySafety}$ algorithm."),
    heading("p0014-b005", [133.0, 556.0, 462.0, 570.0], "## 4 Reasoning principles for trace containment"),
    text("p0014-b006", [133.0, 581.0, 478.0, 669.0],
         r"For a fixed unsafe set $\mathcal{U}$ and two hybrid systems $\mathcal{H}_1$ and $\mathcal{H}_2$, proving $\mathsf{Reach}_{\mathcal{H}_1} \subseteq \mathsf{Reach}_{\mathcal{H}_2}$ and the safety of $\mathcal{H}_2$, allows us to conclude the safety of $\mathcal{H}_1$. Proposition 2.9 establishes that proving containment of traces, trajectories, and initial sets of two hybrid systems, ensures the containment of their respective reach sets. These two observations together give us a method of concluding the safety of one system, from the safety of another, provided we can check trace containment of two graphs, and trajectory containment of two trajectory sets. In our examples, the set of modes $\text{Ł}$ and the set of trajectories $\mathcal{TL}$ is often the same"),
    pageno(14, [300.0, 695.0, 311.0, 703.0]),
]

save(14, items, r"""
Compared with a 190-dpi render of the text block, a 330-dpi crop of the table, and experiments.tex / theory.tex. ORDER CHANGED: Table 1 is a float printed at the top of the page, in the middle of the sentence 'as A | overtakes B (bottom plot)' that runs over from page 13. The continuing text is the first item (join_previous 'space'); Table 1, its caption and a conversion note follow it, directly before the paragraph 'Table 1 summarizes ...'. Table 1: transcribed as cells (9 rows x 7 columns including the header) and compared cell by cell with the 330-dpi crop: TH 80/50, all interval end points (note $sx_A \in [-5,5]$ in the two Merge rows, $sy_B \in [4,6.5]$ in the unsafe AutoPassing row), Ref 2, 4, 5, 0, -, 4, -, 2, the check/cross marks and the runtimes 217.4s, 208.4s, 152.5s, 55.0s, 38.7s, 197.6s, 21.3s, 109.2s. The extractor's cells contained emphasis markers, control characters for the check/cross marks and split model labels; all rewritten. Cells are plain Unicode strings (the builder doubles backslashes in table cells): 'λ ∈ [14.6, 14.8]', 'sy_A ∈ [-1, 1] sy_B ∈ [14, 16]', '✓', '✗'; ASCII hyphen for the minus signs; a space was added after the commas inside intervals. The Model cells that span two printed rows are repeated in both CSV rows with the full label; this and the other representation choices are stated in the conversion-note item placed after the caption (its bbox is the empty strip between table and caption; it is not text of the paper). Caption verbatim ('#' as printed). Text: unsafe set $(|sx_A-sx_B|<2 \ \&\ |sy_A-sy_B|<2)$ from the TeX, checked; '[30, 40]' with a space after the comma. Extractor damage fixed: 'i76600U' -> 'i7-6600U' (real hyphen at a line end, per the TeX); line-wrap hyphens removed (gener-ated, addi-tion, ex-ecutions, Proposi-tion, contain-ment). Authors' wording kept: 'finds counter-example', 'range ... are shown'. '4 Reasoning principles for trace containment' is a numbered section (##). References as printed: 'Figure 2b', 'Table 1', 'Appendix A.2', 'Proposition 2.9'. 'Ł' for \L as printed. The last paragraph continues on page 15. Omitted: page number 14.
""")
