from pagelib import *
P = 19
items = [
    text("p0019-b000", B(P, "p0019-b000"),
         r"**Lemma 1:** We can first demonstrate that $\delta \theta_{k+1}$ is square integrable. In particular,"),
    display("p0019-b001", B(P, "p0019-b001"), r"""\begin{aligned}
&\mathbb{E}[||\delta \theta_{k+1}||^2 | \mathcal{F}_{\theta,k}]\\
&\leq 2 || \nabla_\theta \log \pi(a|s; \theta)|_{\theta=\theta_k} \mathbb{1}_{\pi(a|s;\theta_k) > 0}||^2_\infty \cdot \bigg(||Q(s,a;\eta_k)||^2_\infty \cdot ||1 - p_{\xi_k}(s)||^2_\infty \\
&+ ||Q_c(s,a;\kappa_k)||^2_\infty \cdot \biggl[||\lambda_\omega||^2_\infty \cdot ||1 - p_{\xi_k}(s)||^2_\infty + ||p_{\xi_k}(s)||^2_\infty\biggr]\bigg) \\
&\leq 2 \frac{|| \nabla_\theta \pi(a|s; \theta)|_{\theta=\theta_k}||^2_\infty}{\min\{ \pi(a|s;\theta_k) | \pi(a|s;\theta_k) > 0\}} \cdot \bigg(||Q(s,a;\eta_k)||^2_\infty \cdot ||1 - p_{\xi_k}(s)||^2_\infty \\
&+ ||Q_c(s,a;\kappa_k)||^2_\infty \cdot \biggl[||\lambda_\omega||^2_\infty \cdot ||1 - p_{\xi_k}(s)||^2_\infty + ||p_{\xi_k}(s)||^2_\infty\biggr]\bigg)
\end{aligned}"""),
    text("p0019-b002", B(P, "p0019-b002"),
         r"Note that $\mathcal{F}_{\theta,k}=\sigma(\theta_m, \delta \theta_m, m\leq k)$ is the filtration for $\theta_k$ generated by different independent trajectories [8]. Also note that the indicator function is used because the expectation of $||\delta \theta_{k+1}||^2$ is taken with respect to $P^{\pi_{\theta_k}}$ and $P^{\pi_{\theta_k}}(s,a|s_0)=0$ if $\pi(a|s;\theta_k)=0$. From the Assumptions on Lipschitz continuity and Finite MDPs reward and costs, we can bound the values of the functions and the gradients of functions. Specifically"),
    display("p0019-b003", B(P, "p0019-b003"), r"""\begin{aligned}
|| \nabla_\theta \pi(a|s; \theta)|_{\theta=\theta_k}||^2_\infty &\leq K_1(1 + ||\theta_k||^2_\infty),\\
||Q(s,a;\eta_k)||^2_\infty &\leq \frac{R_{\max}}{1-\gamma}, \\
||Q_h(s,a;\kappa_k)||^2_\infty &\leq \frac{H_{\max}}{1-\gamma}, \\
||\lambda_\omega||^2_\infty &\leq \lambda_{\max}, \\
||1 - p_{\xi_k}(s)||^2_\infty &\leq 1, \\
||p_{\xi_k}(s)||^2_\infty &\leq 1
\end{aligned}"""),
    text("p0019-b004", B(P, "p0019-b004"),
         r"where $K_1$ is a Lipschitz constant. Furthermore, note that because we are sampling, $\pi(a|s;\theta_k)$ will take on only a finite number of values, so its nonzero values will be bounded away from zero. Thus we can say"),
    display("p0019-b005", B(P, "p0019-b005"),
            r"\frac{1}{\min\{ \pi(a|s;\theta_k) | \pi(a|s;\theta_k) > 0\}} \leq K_2"),
    text("p0019-b006", B(P, "p0019-b006"),
         r"for some large enough $K_2$. Thus using the bounds from these conditions, we can demonstrate"),
    display("p0019-b007", B(P, "p0019-b007"),
            r"\mathbb{E}[||\delta \theta_{k+1}||^2 | \mathcal{F}_{\theta,k}] \leq 2\cdot K_1(1 + ||\theta_k||^2_\infty)\cdot K_2(\frac{R_{\max}}{1-\gamma}\cdot 1 + \frac{H_{\max}}{1-\gamma}\cdot(\lambda_{\max}\cdot 1 + 1)) < \infty"),
    text("p0019-b008", B(P, "p0019-b008"),
         r"Therefore $\delta \theta_{k+1}$ is square integrable."),
    text("p0019-b009", B(P, "p0019-b009"),
         r"**Lemma 2:** Secondly, we can demonstrate $\delta \theta_\epsilon\rightarrow 0$."),
    display("p0019-b010", B(P, "p0019-b010"), r"""\begin{aligned}
&\delta \theta_\epsilon = \sum_{s_i,a_i} d_0(s_0)P^{\pi_{\theta_k}}(s_i,a_i|s_0)\biggl[\gamma^i \bigl[(Q(s_i,a_i;\eta_k)-Q^{\pi_{\theta_k}}(s_i)) [1 - p_{\xi_k}(s_i)] \\
&+ (-Q_c(s_i,a_i; \kappa_k)+Q^{\pi_{\theta_k}}_c(s_i,a_i)) [\lambda_\omega (1 - p_{\xi_k}(s_i)) + p_{\xi_k}(s_i)]\bigr]\nabla_\theta \log \pi(a_i | s_i; \theta) |_{\theta=\theta_k}\biggr]\\
&\leq \sum_{s_i,a_i} d_0(s_0)P^{\pi_{\theta_k}}(s_i,a_i|s_0)\biggl[\gamma^i \bigl[(Q(s_i,a_i;\eta_k)-Q(s_i,a_i;\eta^{\ast})) [1 - p_{\xi_k}(s_i)] \\
&+ (-Q_c(s_i,a_i; \kappa_k)+Q_c(s_i,a_i; \kappa^{\ast})) [\lambda_\omega (1 - p_{\xi_k}(s_i)) + p_{\xi_k}(s_i)]\bigr]\nabla_\theta \log \pi(a_i | s_i; \theta) |_{\theta=\theta_k}\biggr]\\
&\leq \sum_{s_i,a_i} d_0(s_0)P^{\pi_{\theta_k}}(s_i,a_i|s_0)\biggl[\gamma^i \bigl[||Q(s_i,a_i;\eta_k)-Q(s_i,a_i;\eta^{\ast})|| [1 - p_{\xi_k}(s_i)] \\
&+ ||-Q_c(s_i,a_i; \kappa_k)+Q_c(s_i,a_i; \kappa^{\ast})|| [\lambda_\omega (1 - p_{\xi_k}(s_i)) + p_{\xi_k}(s_i)]\bigr]\nabla_\theta \log \pi(a_i | s_i; \theta) |_{\theta=\theta_k}\biggr]
\end{aligned}"""),
    pageno(P),
]
save(P, items, r"""
Compared with a 170 dpi render of PDF page 19, a 200 dpi crop of the Lemma 2 display, and with main.tex (Step 2 of the
convergence proof: Lemma 1 and Lemma 2). The page is almost entirely mathematics; all five displays (extractor formula
images) were rewritten in LaTeX from the TeX source and checked line by line on the render; TeX and PDF agree. None is
numbered. Display 1 (five lines): the bound on $\mathbb{E}[||\delta\theta_{k+1}||^2|\mathcal{F}_{\theta,k}]$ with the
indicator $\mathbb{1}_{\pi(a|s;\theta_k)>0}$ in the first inequality and the fraction with
$\min\{\pi(a|s;\theta_k)|\pi(a|s;\theta_k)>0\}$ in the second. Display 2 (six lines, aligned at the inequality sign,
commas after the first five lines, none after the last): the six bounds; as printed the third one is for
$Q_h(s,a;\kappa_k)$ (subscript h; the cost critic is $Q_c$ elsewhere), and the bounds are stated for the squared
sup-norms. Display 3: the bound by $K_2$. Display 4: the final finite bound, with ordinary (not enlarged) parentheses
after $K_2$ as printed. Display 5 (six lines, Lemma 2): as printed the first line has $Q^{\pi_{\theta_k}}(s_i)$ with
the single argument $s_i$, and the chain uses '$\leq$' twice. The norms are typed with double bars '||' and the
conditioning bars and restriction bars with single '|', as in the source. 'Lemma 1' and 'Lemma 2' are printed in
italics followed by an upright colon; they are informal lemmas inside the proof (run-in text, not a lemma
environment) and are written with a bold label '**Lemma 1:**' / '**Lemma 2:**'. Asterisks written \ast. Citation [8]
checked. The Lemma 2 display ends at the foot of the page; the proof continues on page 20 ('And because we have ...').
Omitted: printed page number 19.
""")
