from pagelib import *
P = 22
RS = r"|_{\theta=\theta^{\ast}(\omega),\xi=\xi^{\ast}(\omega)}"
LS = r"L(\theta^{\ast}(\omega),\xi^{\ast}(\omega),\omega)"
LSS = r"L(\theta^{\ast}(\omega),\xi^{\ast}(\omega),\omega^{\ast})"
items = [
    text("p0022-b000", B(P, "p0022-b000"),
         r"for some large Lipschitz constant $K_3$. Note that $\mathcal{F}_{\omega,k}=\sigma(\omega_m, \delta \omega_m, m\leq k)$ is the filtration for $\omega_k$ generated by different independent trajectories [8]."),
    text("p0022-b001", B(P, "p0022-b001"),
         r"**Lemma 5:** Because $||Q_c(s_t, a_t; \kappa_k)-Q^{\pi_{\theta_k}}_c(s_t, a_t)||_\infty \rightarrow 0$ and $||p^\diamond(s_t)-p(s_t; \xi_k)||_\infty \rightarrow 0$ and $Q^{\pi_{\theta_k}}_c(s_t, a_t)[1-p_{\xi^{\ast}}(s_t)] \nabla_\omega \lambda_\omega |_{\omega=\omega_k}$ is a sample of $Q^{\pi_{\theta^{\ast}}}_c(s_i,a_i)[1-p_{\xi^{\ast}}(s_i)]\nabla_\omega \lambda_\omega |_{\omega=\omega_k}$, we conclude that $\mathbb{E}[\delta \omega_{k+1} | \mathcal{F}_{\omega, k}]=0$ almost surely."),
    text("p0022-b002", B(P, "p0022-b002"),
         r"Thus, the lagrange multiplier $\omega$ update is a stochastic approximation of a continuous system $\omega(t)$ defined by [10]"),
    display("p0022-b003", B(P, "p0022-b003"),
            r"\dot{\omega} = \Upsilon_\Omega[-\nabla_\omega L(\theta, \xi, \omega)" + RS + r"] \tag{9}"),
    text("p0022-b004", B(P, "p0022-b004"),
         r"with Martingale difference error of $\delta \omega_k$ and where $\Upsilon_\Omega$ is the left direction derivative defined similar to that in Time scale 2 of the convergence of $\theta$ update. Using Step 2 in Appendix A.2 from [8], we have that $d" + LS + r"/dt=\nabla_\omega {L(\theta,\xi,\omega)" + RS + r"}^T\cdot \Upsilon_\Omega[\nabla_\Omega L(\theta, \xi, \omega)" + RS + r"] \geq 0$ and the value is non-zero if $||\Upsilon_\Omega[\nabla_\omega L(\theta, \xi, \omega)" + RS + r"]|| \neq 0$."),
    text("p0022-b005", B(P, "p0022-b005"),
         r"For a local maximum point $\omega^{\ast}$, define a Lyapunov function as"),
    display("p0022-b006", B(P, "p0022-b006"),
            r"\mathcal{L}(\omega) = " + LSS + " - " + LS),
    text("p0022-b007", B(P, "p0022-b007"),
         r"Then there exists a ball centered at $\omega^{\ast}$ with a radius $\rho'$ such that $\forall \omega\in \mathfrak{B}_{\omega^{\ast}}(\rho')=\{\omega | ||\omega - \omega^{\ast}|| \leq \rho'  \}$, $\mathcal{L}(\omega)$ is a locally positive definite function, that is $\mathcal{L}(\omega) \geq 0$. Also, $d\mathcal{L}(\omega(t))/dt = -d" + LS + r"/dt\leq 0$ and is equal only when $\Upsilon_\Omega[\nabla_\omega L(\theta, \xi, \omega)" + RS + r"] = 0$, so therefore $\omega^{\ast}$ is a stationary point. By leveraging Lyapunov theory for asymptotically stable systems presented in Chapter 4 of [55] we can demonstrate that for any initial conditions of $\omega \in \mathfrak{B}_{\omega^{\ast}}(\rho')$, the continuous state trajectory of $\omega(t)$ converges to the locally maximum point $\omega^{\ast}$."),
    text("p0022-b008", B(P, "p0022-b008"),
         r"Using these aforementioned properties, as well as the facts that 1) $\nabla_\omega L(\theta^{\ast}(\omega), \xi^{\ast}(\omega), \omega)$ is a Lipschitz function, 2) the step-sizes of Assumption on steps sizes, 3) $\{ \omega_{k+1} \}$ is a stochastic approximation of $\omega(t)$ with a Martingale difference error, and 4) convex and compact properties in projections used, we can use Theorem $2$ of chapter $6$ in [10] to demonstrate the sequence $\{\omega_k\}$ converges almost surely to a locally maximum point $\omega^{\ast}$ almost surely, that is $" + LSS + r" \geq " + LS + r"$."),
    text("p0022-b009", B(P, "p0022-b009"),
         r"From Time scales $2$ and $3$ we have that $" + LS + r" \leq L(\theta, \xi, \omega)$ while from Time scale $4$ we have that $" + LSS + r" \geq " + LS + r"$. Thus, $" + LS + r"  \leq " + LSS + r" \leq L(\theta, \xi, \omega^{\ast})$. Therefore, $(\theta^{\ast},\xi^{\ast},\omega^{\ast})$ is a local saddle point of $(\theta,\xi,\omega)$. Invoking the saddle point theorem of Proposition 5.1.6 in [54], we can conclude that $\pi(\cdot|\cdot; \theta^{\ast})$ is a locally optimal policy for our proposed optimization formulation. $\square$"),
    heading("p0022-b010", B(P, "p0022-b010"), "#### C.4.4 Remark on Bounding Lagrange Multiplier"),
    text("p0022-b011", B(P, "p0022-b011"),
         r"We can say our algorithm learns an REF that is closer to an optimally safe policy’s REF as we take $\lambda_{\max}\rightarrow\infty$. Nonetheless, we want to put a bound on the $\lambda_{\max}$. This $\lambda_{\max}$ must be large enough so that choosing a policy that can reduce the expected cost returns by some non-zero amount is prioritized over increasing the reward returns. So any change in the reward critic terms must be less than any change in the cost critic term. If $H_{\Delta}$ is the minimum non-zero difference between any two cost values, and $P_{\min}$ is the minimum sampled non-zero likelihood of reaching a particular state and a point in the sample trajectory, then we can bound the maximum change in the reward returns and the maximum change on the weighted cost returns:"),
    display("p0022-b012", B(P, "p0022-b012"), r"""\begin{aligned}
\Delta \mathbb{E}_{s\sim d_0}[ V(s)] &\leq \frac{R_{\max}}{1-\gamma} \\
\gamma^T\cdot H_{\Delta}\cdot P_{\min}\cdot (\lambda + \frac{\phi(s)}{(1 - \phi(s))}) &\leq \Delta \mathbb{E}_{s\sim d_0} [V_c(s)\cdot (\lambda + \frac{\phi(s)}{(1 - \phi(s))})]
\end{aligned}"""),
    pageno(P),
]
save(P, items, r"""
Compared with a 170 dpi render of PDF page 22 and with main.tex (end of Step 4 and of the convergence proof; start of
C.4.4). All mathematics rewritten in LaTeX from the TeX source and checked on the render; TeX and PDF agree. The first
item completes the sentence of the Lemma 4 display at the foot of page 21 ('... $<\infty$ | for some large Lipschitz
constant $K_3$'); it follows a display, so no join is used. Displays: (9) the projected ODE for $\omega$ (numbered);
the unnumbered Lyapunov function $\mathcal{L}(\omega)$; the unnumbered two-line display of C.4.4 aligned at the
inequality signs. As printed (kept): in the paragraph after (9) the transpose is attached to the restricted gradient
and the gradient inside $\Upsilon_\Omega$ carries a capital subscript, $\nabla_\Omega$, in the first formula but
$\nabla_\omega$ in the norm; (9) has a minus sign inside $\Upsilon_\Omega[\cdot]$ while the following formulas have
none; 'left direction derivative'; 'converges almost surely to a locally maximum point $\omega^{\ast}$ almost surely'
(doubled); 'the step-sizes of Assumption on steps sizes'; the ball is a Fraktur B with radius $\rho'$; in C.4.4 the
symbol $\phi(s)$ is written without superscript, the parentheses around the fractions are of ordinary size, and
$H_{\Delta}$ and $P_{\min}$ are defined in the prose. Math-mode numerals ('Theorem $2$ of chapter $6$', 'Time scales
$2$ and $3$', 'Time scale $4$') and plain ones ('Time scale 2', 'Step 2 in Appendix A.2 from [8]', 'Chapter 4 of
[55]', 'Proposition 5.1.6 in [54]') as in the source. 'Lemma 5' printed in italics with an upright colon (bold label
here). The end-of-proof box of the convergence proof is printed at the end of the last line of the saddle-point
paragraph and is written as a square symbol. Line-wrap hyphens removed ('conclude', 'derivative', 'Using',
'Lipschitz', 'Invoking'). Citations [8], [10], [55], [54] checked. Heading C.4.4 level 4. The remark continues on page
23. Omitted: printed page number 22.
""")
